export const screens = [
  {
    name: 'welcome_to_samtli',
    reference: 'docs/design-reference/stitch-export/welcome_to_samtli/screen.png',
    route: '/',
    auth: 'guest',
    state: 'guest-full-page',
    variant: 'canonical-public-home',
    notes: 'Intentional production deviation: Stitch shows About, but Samtli has no About route or section, so the real header omits that dead-end nav item.',
    tags: ['full-page', 'guest'],
  },
  {
    name: 'samtli_welcome_hampus',
    reference: 'docs/design-reference/stitch-export/samtli_welcome_hampus/screen.png',
    route: '/',
    auth: 'member',
    state: 'authenticated-home',
    variant: 'authenticated-home-variant',
    tags: ['full-page', 'authenticated'],
  },
  {
    name: 'home_samtli',
    reference: 'docs/design-reference/stitch-export/home_samtli/screen.png',
    route: '/',
    auth: 'member',
    state: 'authenticated-home',
    variant: 'canonical-authenticated-home',
    tags: ['full-page', 'authenticated'],
  },
  {
    name: 'samtli_home_feed',
    reference: 'docs/design-reference/stitch-export/samtli_home_feed/screen.png',
    route: '/',
    auth: 'member',
    state: 'authenticated-home-with-feed',
    variant: 'feed-component-reference',
    tags: ['full-page', 'authenticated', 'shared-component-reference'],
  },
  {
    name: 'samtli_wordmark',
    reference: 'docs/design-reference/stitch-export/samtli_wordmark/screen.png',
    route: '/',
    auth: 'guest',
    state: 'header-wordmark',
    variant: 'reference-only-wordmark',
    tags: ['shared-component-reference'],
  },
  {
    name: 'register_samtli_1',
    reference: 'docs/design-reference/stitch-export/register_samtli_1/screen.png',
    route: '/register',
    auth: 'guest',
    state: 'registration-form',
    variant: 'registration-variant',
    tags: ['full-page', 'guest', 'form'],
  },
  {
    name: 'register_samtli_2',
    reference: 'docs/design-reference/stitch-export/register_samtli_2/screen.png',
    route: '/register',
    auth: 'guest',
    state: 'registration-form',
    variant: 'canonical-registration',
    notes: 'Intentional production deviation: Stitch mobile chrome includes Profile, but Samtli has no profile route yet, so production mobile nav only links to real routes.',
    tags: ['full-page', 'guest', 'form'],
  },
  {
    name: 'create_account_samtli',
    reference: 'docs/design-reference/stitch-export/create_account_samtli/screen.png',
    route: '/register',
    auth: 'guest',
    state: 'registration-form-invitation-context',
    variant: 'registration-context-reference',
    tags: ['full-page', 'guest', 'form', 'invitation-state'],
  },
  {
    name: 'log_in_samtli_1',
    reference: 'docs/design-reference/stitch-export/log_in_samtli_1/screen.png',
    route: '/login',
    auth: 'guest',
    state: 'login-form',
    variant: 'login-variant',
    tags: ['full-page', 'guest', 'form'],
  },
  {
    name: 'log_in_samtli_2',
    reference: 'docs/design-reference/stitch-export/log_in_samtli_2/screen.png',
    route: '/login',
    auth: 'guest',
    state: 'login-form',
    variant: 'canonical-login',
    tags: ['full-page', 'guest', 'form'],
  },
  {
    name: 'log_in_error_samtli',
    reference: 'docs/design-reference/stitch-export/log_in_error_samtli/screen.png',
    route: '/login',
    auth: 'guest',
    setup: 'submit-invalid-login',
    state: 'login-error',
    variant: 'login-error-state',
    tags: ['full-page', 'guest', 'form', 'error-state'],
  },
  {
    name: 'discover_samtli_1',
    reference: 'docs/design-reference/stitch-export/discover_samtli_1/screen.png',
    route: '/groups',
    auth: 'member',
    state: 'discover-groups',
    variant: 'canonical-discover',
    tags: ['full-page', 'authenticated', 'member-state'],
  },
  {
    name: 'discover_samtli_2',
    reference: 'docs/design-reference/stitch-export/discover_samtli_2/screen.png',
    route: '/groups',
    auth: 'member',
    state: 'discover-groups',
    variant: 'discover-variant',
    notes: 'Intentional production deviation: mobile bottom navigation uses Home, Explore, and Account because these are implemented product routes.',
    tags: ['full-page', 'authenticated', 'member-state'],
  },
  {
    name: 'create_group_samtli',
    reference: 'docs/design-reference/stitch-export/create_group_samtli/screen.png',
    route: '/groups/create',
    auth: 'member',
    state: 'create-group-form',
    variant: 'canonical-create-group',
    tags: ['full-page', 'authenticated', 'form'],
  },
  {
    name: 'photography_group_samtli_1',
    reference: 'docs/design-reference/stitch-export/photography_group_samtli_1/screen.png',
    routeKey: 'photographyGroup',
    auth: 'admin',
    state: 'group-detail-with-discussions',
    variant: 'canonical-group-detail',
    tags: ['full-page', 'administrator-state'],
  },
  {
    name: 'photography_group_samtli_2',
    reference: 'docs/design-reference/stitch-export/photography_group_samtli_2/screen.png',
    routeKey: 'photographyGroup',
    auth: 'admin',
    state: 'group-detail-with-discussions',
    variant: 'group-detail-variant',
    tags: ['full-page', 'administrator-state'],
  },
  {
    name: 'photography_group_guest_samtli',
    reference: 'docs/design-reference/stitch-export/photography_group_guest_samtli/screen.png',
    routeKey: 'photographyGroup',
    auth: 'outsider',
    state: 'non-member-group-forbidden',
    variant: 'assignment-conflict-reference',
    notes: 'Current assignment security forbids non-member group detail access; compared to real forbidden state rather than exposing private group content.',
    tags: ['full-page', 'guest-state', 'member-state'],
  },
  {
    name: 'photography_group_empty_samtli',
    reference: 'docs/design-reference/stitch-export/photography_group_empty_samtli/screen.png',
    routeKey: 'emptyGroup',
    auth: 'admin',
    state: 'empty-group',
    variant: 'canonical-empty-group',
    tags: ['full-page', 'administrator-state', 'empty-state'],
  },
  {
    name: 'joined_photography_samtli',
    reference: 'docs/design-reference/stitch-export/joined_photography_samtli/screen.png',
    routeKey: 'photographyGroup',
    auth: 'member',
    state: 'joined-group',
    variant: 'success-state-reference',
    tags: ['full-page', 'member-state', 'success-state'],
  },
  {
    name: 'start_discussion_photography_samtli',
    reference: 'docs/design-reference/stitch-export/start_discussion_photography_samtli/screen.png',
    routeKey: 'startDiscussion',
    auth: 'member',
    state: 'start-discussion-form',
    variant: 'canonical-start-discussion',
    tags: ['full-page', 'authenticated', 'form'],
  },
  {
    name: 'discussion_everyday_lens_photography_samtli',
    reference: 'docs/design-reference/stitch-export/discussion_everyday_lens_photography_samtli/screen.png',
    routeKey: 'everydayLensDiscussion',
    auth: 'member',
    state: 'discussion-detail',
    variant: 'canonical-discussion-detail',
    tags: ['full-page', 'authenticated', 'discussion-state'],
  },
  {
    name: 'discussion_everyday_lens_replying_photography_samtli',
    reference: 'docs/design-reference/stitch-export/discussion_everyday_lens_replying_photography_samtli/screen.png',
    routeKey: 'everydayLensDiscussion',
    auth: 'member',
    setup: 'focus-reply-composer',
    state: 'discussion-replying',
    variant: 'reply-composer-state',
    tags: ['full-page', 'authenticated', 'discussion-state', 'form'],
  },
  {
    name: 'everyday_lens_samtli',
    reference: 'docs/design-reference/stitch-export/everyday_lens_samtli/screen.png',
    routeKey: 'everydayLensDiscussion',
    auth: 'member',
    state: 'discussion-detail',
    variant: 'discussion-detail-variant',
    tags: ['full-page', 'authenticated', 'discussion-state'],
  },
  {
    name: 'manage_photography_overview_samtli',
    reference: 'docs/design-reference/stitch-export/manage_photography_overview_samtli/screen.png',
    routeKey: 'photographyGroup',
    auth: 'admin',
    state: 'admin-overview-reference',
    variant: 'reference-only-admin-overview',
    notes: 'No distinct production admin overview route exists; compared against the administrator group landing where admin controls are exposed.',
    tags: ['full-page', 'administrator-state', 'shared-component-reference'],
  },
  {
    name: 'manage_photography_join_requests_samtli',
    reference: 'docs/design-reference/stitch-export/manage_photography_join_requests_samtli/screen.png',
    routeKey: 'joinRequests',
    auth: 'admin',
    state: 'join-requests-with-pending',
    variant: 'canonical-join-requests',
    tags: ['full-page', 'administrator-state'],
  },
  {
    name: 'manage_photography_join_requests_empty_samtli',
    reference: 'docs/design-reference/stitch-export/manage_photography_join_requests_empty_samtli/screen.png',
    routeKey: 'joinRequestsEmpty',
    auth: 'emptyAdmin',
    state: 'join-requests-empty',
    variant: 'empty-join-requests',
    tags: ['full-page', 'administrator-state', 'empty-state'],
  },
  {
    name: 'manage_join_requests_samtli',
    reference: 'docs/design-reference/stitch-export/manage_join_requests_samtli/screen.png',
    routeKey: 'joinRequests',
    auth: 'admin',
    state: 'join-requests-with-pending',
    variant: 'join-requests-variant',
    tags: ['full-page', 'administrator-state'],
  },
  {
    name: 'manage_photography_members_samtli',
    reference: 'docs/design-reference/stitch-export/manage_photography_members_samtli/screen.png',
    routeKey: 'members',
    auth: 'admin',
    state: 'members-admin',
    variant: 'canonical-members',
    tags: ['full-page', 'administrator-state'],
  },
  {
    name: 'manage_photography_invitations_samtli',
    reference: 'docs/design-reference/stitch-export/manage_photography_invitations_samtli/screen.png',
    routeKey: 'invitationsAdmin',
    auth: 'admin',
    state: 'invitations-admin',
    variant: 'canonical-invitations-admin',
    tags: ['full-page', 'administrator-state', 'invitation-state'],
  },
  {
    name: 'invitation_photography_samtli_1',
    reference: 'docs/design-reference/stitch-export/invitation_photography_samtli_1/screen.png',
    routeKey: 'validInvitation',
    auth: 'outsider',
    state: 'valid-invitation',
    variant: 'canonical-invitation',
    tags: ['full-page', 'invitation-state'],
  },
  {
    name: 'invitation_photography_samtli_2',
    reference: 'docs/design-reference/stitch-export/invitation_photography_samtli_2/screen.png',
    routeKey: 'validInvitation',
    auth: 'outsider',
    state: 'valid-invitation',
    variant: 'invitation-variant',
    tags: ['full-page', 'invitation-state'],
  },
  {
    name: 'invitation_unavailable_samtli',
    reference: 'docs/design-reference/stitch-export/invitation_unavailable_samtli/screen.png',
    routeKey: 'expiredInvitation',
    auth: 'guest',
    state: 'unavailable-invitation',
    variant: 'canonical-unavailable-invitation',
    tags: ['full-page', 'invitation-state', 'error-state'],
  },
  {
    name: 'account_samtli',
    reference: 'docs/design-reference/stitch-export/account_samtli/screen.png',
    route: '/account',
    auth: 'member',
    state: 'account-settings',
    variant: 'canonical-account-settings',
    tags: ['full-page', 'authenticated', 'form'],
  },
  {
    name: 'application_states_empty_error_samtli',
    reference: 'docs/design-reference/stitch-export/application_states_empty_error_samtli/screen.png',
    route: '/missing-page',
    auth: 'guest',
    state: 'not-found-state',
    variant: 'application-state-reference',
    tags: ['full-page', 'error-state', 'empty-state'],
  },
  {
    name: 'application_states_ui_feedback_samtli',
    reference: 'docs/design-reference/stitch-export/application_states_ui_feedback_samtli/screen.png',
    route: '/login',
    auth: 'guest',
    setup: 'submit-invalid-login',
    state: 'ui-feedback-reference',
    variant: 'application-state-reference',
    tags: ['full-page', 'error-state', 'form'],
  },
];
